### ISSUE TITLE
Upper boundary missing

### ISSUE THREAD

**Issue by markwalkom** [stormpython/heatmap#16]
In this attached pic, the upper boundary is 100 but it's not shown, so appears to be unbounded.

![screen shot 2016-03-15 at 16 09 48 pm](https://cloud.githubusercontent.com/assets/3184718/13768296/6e74f2ee-eac8-11e5-8bac-b56177d7abfb.jpg)

Can this be added in?

**Comment by stormpython** [comment]
@markwalkom you are absolutely right. I forgot to add the upper limit.

Bug is [here](https://github.com/stormpython/heatmap/blob/master/public/vis/components/visualization/heatmap.js#L156). Should be:

```
.datum([0].concat(colorScale.quantiles()).concat(colorScale.domain()[1]))
```

I will also need to modify the code in the legend [here](https://github.com/stormpython/heatmap/blob/master/public/vis/components/legend/legend.js#L74) to handle the last bucket. 

Something to the extent of:

```
if (i !== data.length - 1) {
  return Math.round(d) + ' - ' + Math.round(data[i + 1]);
}
```

But, there is an issue of an extra `rect` being added that will need to be removed when implementing these changes.

This can be handled by removing the last item in the data array and saving it as a variable. For example:

```
var upperLimit = data.pop();
```

Now, the data binding will create the appropriate number of `g` elements. And [here](https://github.com/stormpython/heatmap/blob/master/public/vis/components/legend/legend.js#L74), I can add:

```
return (i === data.length - 1) ? Math.round(d) + ' - ' Math.round(upperLimit) : Math.round(d) + ' - ' + Math.round(data[i + 1]);
```
