### ISSUE TITLE
The size and the line display is not corresponding

### ISSUE THREAD

**Issue by yhgcn** [stormpython/heatmap#27]
select:
Data->buckets->Rows
Sub Aggregation=Terms
Order=Descending
Size=?

display lines:
if Size=1, Then display line number=3
if Size=2, Then display line number=4
if Size=3, Then display line number=5
if Size=4, Then display line number=8
if Size=5, Then display line number=10
if Size=6, Then display line number=12
if Size=7, Then display line number=16
if Size=8, Then display line number=19
……

**Comment by stormpython** [comment]
@yhgcn I am confused. What do you mean by display line? Could you include screen shots?

**Comment by stormpython** [comment]
Size: 1
<img width="1389" alt="screen shot 2016-04-16 at 7 27 02 am" src="https://cloud.githubusercontent.com/assets/3149785/14581555/ba82f65a-03a4-11e6-9cda-e8186efa3e32.png">

Size: 2
<img width="1391" alt="screen shot 2016-04-16 at 7 27 20 am" src="https://cloud.githubusercontent.com/assets/3149785/14581556/be254204-03a4-11e6-92de-d6fdc859f5e8.png">

Size: 3
<img width="1391" alt="screen shot 2016-04-16 at 7 27 39 am" src="https://cloud.githubusercontent.com/assets/3149785/14581560/cbd43be4-03a4-11e6-9ace-78c1bbd071a7.png">

**Comment by yhgcn** [comment]
Try Size>7

May be the cause of the cache, change a few times more “Size” value will repeat mistakes.

![20160417211520](https://cloud.githubusercontent.com/assets/18245164/14592060/3e8ce182-054d-11e6-942b-03a7aa0fc6d1.png)

![qq 20160417215249](https://cloud.githubusercontent.com/assets/18245164/14592093/a9a4f342-054d-11e6-8223-2a0df22a9c6e.png)

**Comment by yhgcn** [comment]
![20160417211520](https://cloud.githubusercontent.com/assets/18245164/14592060/3e8ce182-054d-11e6-942b-03a7aa0fc6d1.png)

![qq 20160417215249](https://cloud.githubusercontent.com/assets/18245164/14592093/a9a4f342-054d-11e6-8223-2a0df22a9c6e.png)

**Comment by stormpython** [comment]
@yhgcn The issue that you are having has to do with the order of your aggregations. The size of rows represents that max number of items in each `column` bucket. If you want to see a 1:1 match of the `size` in the rows aggregation to the number of rows you see in the visualization, move the rows aggregation above the columns aggregation.

Click here:
![example](https://cloud.githubusercontent.com/assets/3149785/14615526/ecde8c88-055a-11e6-9f39-a421c75a97fd.png)
