### ISSUE TITLE
An option to define buckets

### ISSUE THREAD

**Issue by Prazzy** [stormpython/heatmap#29]
is it possible to define these buckets manually?

![image](https://cloud.githubusercontent.com/assets/274357/14694866/836174a0-0721-11e6-86cd-95e0caf04956.png)

**Comment by stormpython** [comment]
@Prazzy you have the option of choosing between a number of buckets with some limits. See [here](https://cloud.githubusercontent.com/assets/3149785/14652237/554e8502-0628-11e6-8759-9ec002d762a4.gif).
