### ISSUE TITLE
Clicking a cell within heatmap does not work

### ISSUE THREAD

**Issue by sandeepu** [stormpython/heatmap#32]
On a dashboard with multiple panels, clicking on a single plugin (such as table/bar/pie chart) defines filters that update the other plugins. The heatmap does not support similar functionality? Its a great implementation, but missing this key capability.

**Comment by stormpython** [comment]
Currently, this plugin doesn't support filtering on click. It is something I want to add, but it isn't the most straightforward issue to solve. I will be sure to add it as a feature request though.

**Comment by stormpython** [comment]
Opened #33.
