### ISSUE TITLE
please support negative numbers

### ISSUE THREAD

**Issue by kmike82** [stormpython/heatmap#37]
Negative numbers are currently bucketed with whatever the lowest bucket is. In a data set where 0 is more likely to be median than minimum, this throws off the scale completely

**Comment by stormpython** [comment]
@kmike82 would you mind including a screenshot of your issue?

**Comment by kmike82** [comment]
In the heatmap jpg, you can see that the lowest value is 0 (all negative numbers seem to get grouped into 0). I am only showing the lowest 5 aggregations here

In the linechart jpg, you can see that I expect numbers to range between -18000 and 15000

![heatmap](https://cloud.githubusercontent.com/assets/13381162/18183264/2e71a928-7059-11e6-9484-9fdcacac5d82.jpg)
![linechart](https://cloud.githubusercontent.com/assets/13381162/18183265/2e71d22c-7059-11e6-809c-3f54def91dc3.jpg)

Thanks for your work on this. Your plugins are immensely useful

**Comment by stormpython** [comment]
@kmike82 thanks! I am looking into the issue.

**Comment by stormpython** [comment]
Ok, I think I've found the bug [here](https://github.com/stormpython/heatmap/blob/master/public/vis/components/visualization/heatmap.js#L62).

This should be changed to:

``` javascript
var colorDomain = [Math.min(0, d3.min(metrics, metric), Math.max(d3.max(metrics, metric), 1)];
```

I will open a pull request soon.

**Comment by kmike82** [comment]
Thanks!
