### ISSUE TITLE
Error while installing most recent version (with tooltips fix)

### ISSUE THREAD

**Issue by vineetgoel** [stormpython/heatmap#43]
@stormpython thanks for the quick fix. I am still getting the following error when trying to install the plugin. Not sure if this issue is related to the previous one.

```
./kibana plugin -i heatmap -u https://github.com/stormpython/heatmap/archive/master.zip
Installing heatmap
Attempting to transfer from https://github.com/stormpython/heatmap/archive/master.zip
Transferring 1811145 bytes....................
Transfer complete
Extracting plugin archive
Extraction complete
Optimizing and caching browser bundles...
Plugin installation was unsuccessful due to error "Optimizations failure.

    WARNING in ../src/ui/public/vis/schemas.js
    There is another module with an equal name when case is ignored.
    This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
    Rename module if multiple modules are expected or use equal casing if one module is expected.

    WARNING in ../src/ui/public/Vis/Schemas.js
    There is another module with an equal name when case is ignored.
    This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
    Rename module if multiple modules are expected or use equal casing if one module is expected.

    ERROR in ../installedPlugins/heatmap/public/heatmap.js
    Module not found: Error: Cannot resolve 'file' or 'directory' /Users/vineet/kibana-4.5.1-darwin-x64/src/ui/public/template_vis_type/template_vis_type in /Users/vineet/kibana-4.5.1-darwin-x64/installedPlugins/heatmap/public
     @ ../installedPlugins/heatmap/public/heatmap.js 11:32-81
```

**Comment by tkhduracell** [comment]
+1

**Comment by nmqhoan** [comment]
not sure if it is because of the new tooltip. If yes, I will double check and fix it.

**Comment by stormpython** [comment]
@nmqhoan It looks like it may be an issue with file name changes between Kibana versions. Perhaps we can either create separate versions that support older and newer Kibana versions or simply revert back to supporting up to Kibana 4.5 and not master.

**Comment by arpanshah29** [comment]
seems like both related issues were closed citing the other.

**Comment by nmqhoan** [comment]
@stormpython, I'm agreed. I just fix the bug and commit the code in separated branch (https://github.com/stormpython/heatmap/tree/issue-43). It works with Kibaba v4.

![untitled](https://cloud.githubusercontent.com/assets/3593811/18886447/d1799e8a-84e7-11e6-9f80-7b197a6710db.png)

**Comment by nmqhoan** [comment]
@stormpython, should we keep these two separated branches or I will make a PR so you can merge back to master branch.

**Comment by stormpython** [comment]
@nmqhoan just submit a pull request to the master branch for now so we get it working again. Then I can tag it to a release and then we can move the master branch forward.
