### ISSUE TITLE
Add tooltip

### ISSUE THREAD

**Issue by stormpython** [stormpython/heatmap#6]
When mousing over a square within the heatmap, there is no tooltip. A tooltip should be added for mouseovers and should display:
- Row title
- Column title
- Metric value

**Comment by jccq** [comment]
last issue in the way of the first beta? :)

**Comment by stormpython** [comment]
@jccq yes. One final issue before beta. However, I just started a new position not too long ago, so this vis has been put on the back burner for a bit. 

If you are up to it, I always appreciate PRs.

**Comment by jccq** [comment]
i sent you a linkedin message short ago .We'll try to take care of the PR ,
thanks for the effort!

On Wed, Jun 22, 2016 at 4:19 AM, Shelby Sturgis notifications@github.com
wrote:

> @jccq https://github.com/jccq yes. One final issue before beta.
> However, I just started a new position not too long ago, so this vis has
> been put on the back burner for a bit.
> 
> If you are up to it, I always appreciate PRs.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/stormpython/heatmap/issues/6#issuecomment-227632680,
> or mute the thread
> https://github.com/notifications/unsubscribe/AEuGyFoBW4hxYbcmOXyShKbTHSXAnF7Xks5qOKnPgaJpZM4HjXaE
> .

## 

Giovanni Tummarello
CEO - SIREn Solutions

**Comment by vineetgoel** [comment]
@jccq are you guys working on a PR for this enhancement? If yes, is there an ETA?

**Comment by jccq** [comment]
It went into the backburner, but expecially as we're working on a full features pivottable in Kibi however just talked to someone and he'll get it in by next week.

**Comment by jccq** [comment]
Here it is @stormpython , i was wondering will you be maintaining this component as Kibana evolves? 

We need to fork it ourself to add cross index aggregation support in the Kibi edition - given this we would be happy  to maintain it going forward also with compatibility with pure Kibana  (as we're doing for all the other Kibi/Kibana compatible).

**Comment by stormpython** [comment]
@jccq thanks. I have some comments that I will include in the pr.

As far as maintaining this in future Kibana releases. There is actually a [pull request](https://github.com/elastic/kibana/pull/6974) submitted to included it in the core Kibana visualizations. Hopefully, it will be picked up and worked on in the near future. 

But until that happens, feel free to maintain it. Let me know how you want to handle this. I can add your group as administrators to the repo or can move this officially to the Kibi repository. 

And thanks again for all your efforts.

**Comment by jccq** [comment]
Ah great about the PR to kibana, that is really the place it should go for now, we'll be working toward that.

Ok we'll redo the PR according to your indications and then you should - likely - sign Elastic CLA ( is ee that is one of the open issues in the PR) and finish the process yourself. Alternatively, we could drive this, if you add @nmqhoan as administrator.

thanks for the efforts :) this will be very useful

**Comment by stormpython** [comment]
@jccq there are a couple of issues that I want to close in the repo which I hope to get to this week. Thanks for taking the tooltip pr. The code in my comments hasn't been tested, so there may be some issues, and it may be easier to add a third party tooltip so feel free to explore other options.

I will add @nmqhoan as an administrator, and I've signed the Elastic CLA, but it still shows that I haven't. I am not sure how to resolve this, but I left a comment there for the Elastic developers.

**Comment by nmqhoan** [comment]
Sorry as we have to create a new PR due to some technical problem with the previous one
