### ISSUE TITLE
Scrollbar present after re-sizing visualization

### ISSUE THREAD

**Issue by stormpython** [stormpython/heatmap#8]
A visible scrollbar is present after resizing the window.

![visualize_scrollbar](https://cloud.githubusercontent.com/assets/3149785/13340142/d994fb90-dbe2-11e5-851f-143a5ad4efc9.gif)

This may also be related to this [issue](https://github.com/stormpython/tagcloud/issues/6) for another plugin.

**Comment by Prazzy** [comment]
Setting width to 100% works for now.. 

public/vis/index.js

d3.select(this)
        .attr('width', '100%')

![image](https://cloud.githubusercontent.com/assets/274357/13798312/4165b248-ead2-11e5-992b-2a803f1835fd.png)
