### ISSUE TITLE
Dates are not formatted properly

### ISSUE THREAD

**Issue by stormpython** [stormpython/heatmap#9]
When using a `date histogram` aggregation, dates are not formatted properly.

![screen shot 2016-02-25 at 5 14 38 pm](https://cloud.githubusercontent.com/assets/3149785/13340203/5b3f7486-dbe3-11e5-8364-d2defe86dfb8.png)

**Comment by t3chn0m4g3** [comment]
@stormpython Thank you for this plugin! Finally a promising way to drill down on a huge amount of data. Cannot wait for the improvements / bugs to be fixed - I'm happy to support if you need testing.

**Comment by stormpython** [comment]
@t3chn0m4g3 thanks for help with testing. I plan on working on a few of these issues today.

**Comment by erik-stephens** [comment]
Similar issue with ip addresses - they show as the integer version.
